# Generated by Django 4.1.2 on 2022-10-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('linkedin', models.URLField(blank=True, max_length=255)),
                ('github', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Your email')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fname', models.CharField(blank=True, max_length=255)),
                ('lname', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.CharField(blank=True, max_length=255)),
                ('long_bio', models.TextField(blank=True, max_length=500)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('linkedin', models.URLField(blank=True, max_length=255)),
                ('github', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
